version: '3.9'

services:
  aipex-proxy:
    build: 
      context: .
      dockerfile: dockerfile
    image: aipex-proxy:latest
    container_name: aipex-proxy
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped